### ISSUE TITLE
Data Parsing Util and Data Warehouse

### ISSUE THREAD

**Issue by TwixtMaD** [g0vhk-io/g0vhk_legco_web#6]
May I know that is there any data warehouse (or database) to store all of the LegCo documents(first maybe the parsable data)? Cause in `xmls` part, it's downloaded all the document from LegCo.

I would like to propose that we can deploy the database( e.g. Mongo/Cassandra, MySQL etc.) to store all the data which are parsed from `xmls`.

If so,  I think that I would help to develop this part.

**Comment by howawong** [comment]
It is currently stored at MySQL.

**Comment by howawong** [comment]
@TwixtMaD  shall I close this issue? or you want to discuss further?
